# Generated by Django 4.2 on 2023-05-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xabar',
            name='foydalanuvchi',
        ),
        migrations.RemoveField(
            model_name='xabar',
            name='soat',
        ),
        migrations.AlterField(
            model_name='xabar',
            name='sana',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
